services:
- type: web
  name: drivemaps
  env: python
  repo: https://github.com/kaled182/drivemaps
  plan: starter
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  region: frankfurt
  autoDeployTrigger: commit
  envVars:
    - key: SESSION_TYPE
      sync: false
    - key: SESSION_COOKIE_SECURE
      sync: false
    - key: SESSION_COOKIE_NAME
      sync: false
    - key: SECRET_KEY
      sync: false
    - key: MAP_ID
      sync: false
    - key: MAPBOX_TOKEN
      sync: false
    - key: FLASK_ENV
      sync: false
version: "1"
